// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxswgjkrfqtgzjncaizz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4c3dnamtyZnF0Z3pqbmNhaXp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4ODg5NjQsImV4cCI6MjA2NjQ2NDk2NH0.srDaEolEksr8hO1TZ3Qkg02l1nMXiLx3577XCjl33zA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);